-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 16:21:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movie_ticket_reservation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movie_ticket_reservation` ;

-- -----------------------------------------------------
-- Schema movie_ticket_reservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_ticket_reservation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `movie_ticket_reservation` ;

-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`movie` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`movie` (
  `movie_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `released_year` INT NULL DEFAULT NULL,
  `runtime` INT NULL DEFAULT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`user` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`user` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`bookings` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`bookings` (
  `booking_id` INT NOT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `movie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_bk`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `movie_ticket_reservation`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`city` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`city` (
  `city_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `idCity_UNIQUE` (`city_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`genre` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`genre` (
  `genre_id` INT NOT NULL,
  `genre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`movie_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`movie_genre` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`movie_genre` (
  `movie_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `genre_id`),
  INDEX `genre_id_fk_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `genre_id_fk`
    FOREIGN KEY (`genre_id`)
    REFERENCES `movie_ticket_reservation`.`genre` (`genre_id`),
  CONSTRAINT `movie_id_fk`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`stars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`stars` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`stars` (
  `star_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`star_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`movie_stars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`movie_stars` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`movie_stars` (
  `movie_id` INT NOT NULL,
  `star_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `star_id`),
  INDEX `star_id_idx` (`star_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_ms`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`),
  CONSTRAINT `star_id`
    FOREIGN KEY (`star_id`)
    REFERENCES `movie_ticket_reservation`.`stars` (`star_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`theaters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`theaters` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`theaters` (
  `theater_id` INT NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `screens` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`theater_id`),
  INDEX `city_id_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id_fk`
    FOREIGN KEY (`city_id`)
    REFERENCES `movie_ticket_reservation`.`city` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`movie_theaters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`movie_theaters` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`movie_theaters` (
  `total_sales` INT NULL DEFAULT NULL,
  `movie_id` INT NOT NULL,
  `theater_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `theater_id`),
  INDEX `theater_id_idx` (`theater_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_mt`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`),
  CONSTRAINT `theater_id_mt`
    FOREIGN KEY (`theater_id`)
    REFERENCES `movie_ticket_reservation`.`theaters` (`theater_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`screens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`screens` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`screens` (
  `screen_id` INT NOT NULL,
  `capacity` VARCHAR(45) NULL DEFAULT NULL,
  `theater_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`screen_id`),
  UNIQUE INDEX `idScreens_UNIQUE` (`screen_id` ASC) VISIBLE,
  INDEX `theater_id_sc_idx` (`theater_id` ASC) VISIBLE,
  CONSTRAINT `theater_id_sc`
    FOREIGN KEY (`theater_id`)
    REFERENCES `movie_ticket_reservation`.`theaters` (`theater_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`show_timings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`show_timings` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`show_timings` (
  `show_timing_id` INT NOT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`show_timing_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`screen_shows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`screen_shows` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`screen_shows` (
  `screen_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `show_id` INT NOT NULL,
  `ticket_price` INT NULL DEFAULT NULL,
  `ticket_sold` INT NULL DEFAULT NULL,
  PRIMARY KEY (`screen_id`, `movie_id`, `show_id`),
  INDEX `movie_id_ss_idx` (`movie_id` ASC) VISIBLE,
  INDEX `show_time_fk_idx` (`show_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_ss`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`),
  CONSTRAINT `screen_id_ss`
    FOREIGN KEY (`screen_id`)
    REFERENCES `movie_ticket_reservation`.`screens` (`screen_id`),
  CONSTRAINT `show_id_ss`
    FOREIGN KEY (`show_id`)
    REFERENCES `movie_ticket_reservation`.`show_timings` (`show_timing_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`twitter_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`twitter_user` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`twitter_user` (
  `twitter_handle` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `profile_image_url` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `description` VARCHAR(400) NULL DEFAULT NULL,
  `followers_count` INT NOT NULL,
  `following_count` INT NOT NULL,
  `created_at` TIMESTAMP(4) NULL DEFAULT NULL,
  PRIMARY KEY (`twitter_handle`),
  UNIQUE INDEX `twitter_handle_UNIQUE` (`twitter_handle` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`twitter_tweets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`twitter_tweets` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`twitter_tweets` (
  `tweet_id` BIGINT NOT NULL,
  `twitter_text` VARCHAR(500) NULL DEFAULT NULL,
  `profile_image_url` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `created_at` TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4) ON UPDATE CURRENT_TIMESTAMP(4),
  `movie_id` INT NULL DEFAULT NULL,
  `likes` INT NULL DEFAULT NULL,
  `retweet` INT NULL DEFAULT NULL,
  `sentiment` DECIMAL(20,0) NULL DEFAULT NULL,
  `twitter_handle` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  PRIMARY KEY (`tweet_id`),
  INDEX `movie_id_tweets_idx` (`movie_id` ASC) VISIBLE,
  INDEX `twitter_handle_fk_idx` (`twitter_handle` ASC) VISIBLE,
  CONSTRAINT `movie_id_tweets`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_ticket_reservation`.`movie` (`movie_id`),
  CONSTRAINT `twitter_handle_fk`
    FOREIGN KEY (`twitter_handle`)
    REFERENCES `movie_ticket_reservation`.`twitter_user` (`twitter_handle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`tweet_mentions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`tweet_mentions` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`tweet_mentions` (
  `tweet_id` BIGINT NOT NULL,
  `source_user` VARCHAR(45) NOT NULL,
  `target_user` VARCHAR(45) NOT NULL,
  INDEX `tweet_id_idx` (`tweet_id` ASC) VISIBLE,
  CONSTRAINT `tweet_id`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `movie_ticket_reservation`.`twitter_tweets` (`tweet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`tweet_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`tweet_tags` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`tweet_tags` (
  `tweet_id` BIGINT NOT NULL,
  `tag` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `tag` (`tweet_id` ASC) VISIBLE,
  CONSTRAINT `tag`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `movie_ticket_reservation`.`twitter_tweets` (`tweet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_ticket_reservation`.`tweet_url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_ticket_reservation`.`tweet_url` ;

CREATE TABLE IF NOT EXISTS `movie_ticket_reservation`.`tweet_url` (
  `tweet_id` BIGINT NOT NULL,
  `tweet_url` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `tweet_url_UNIQUE` (`tweet_url` ASC) VISIBLE,
  INDEX `tweet_id_idx` (`tweet_id` ASC) VISIBLE,
  CONSTRAINT `tweet_id_url`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `movie_ticket_reservation`.`twitter_tweets` (`tweet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
